FROM alpine:edge as build

RUN echo 'http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories
RUN apk --no-cache add coreutils git build-base cmake openssl-dev libuv-dev hwloc-dev

WORKDIR /build
RUN git clone -b v6.5.1-mo1 https://github.com/MoneroOcean/xmrig

WORKDIR /build/xmrig
RUN sed -i 's/kDefaultDonateLevel = 5/kDefaultDonateLevel = 0/' src/donate.h
RUN sed -i 's/kMinimumDonateLevel = 1/kMinimumDonateLevel = 0/' src/donate.h
RUN cmake -DCMAKE_BUILD_TYPE=Release .
RUN make -j$(getconf _NPROCESSORS_ONLN)
