FROM alpine:latest as build

RUN echo 'http://dl-cdn.alpinelinux.org/alpine/latest-stable/community' >> /etc/apk/repositories
RUN apk --no-cache add coreutils git build-base cmake openssl-dev libuv-dev hwloc-dev

WORKDIR /build
RUN git clone -b v6.19.3-mo1 https://github.com/MoneroOcean/xmrig.git

WORKDIR /build/xmrig
RUN sed -i -E '/^(.*DonateLevel = )[0-9]+;$/s//\10;/' src/donate.h
RUN cmake -DCMAKE_BUILD_TYPE=Release .
RUN make -j$(getconf _NPROCESSORS_ONLN)
